# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mk', models.CharField(max_length=100)),
            ],
        ),
    ]
