# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0003_post_mk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mk',
            old_name='mk',
            new_name='kategori',
        ),
    ]
