# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0004_auto_20221113_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='dosen',
            field=models.CharField(max_length=255),
        ),
    ]
