# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0006_auto_20221114_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelas', models.CharField(max_length=1)),
            ],
        ),
    ]
