# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 17:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('matkul', '0007_kelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='kelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='matkul.Kelas'),
        ),
    ]
