# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-11-13 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mahasiswa',
            new_name='Guest',
        ),
    ]
